baseURL = "https://meik2333.com"
languageCode = "zh-cn"
title = "MeiK's blog"
theme = "github-style"
googleAnalytics = "UA-107784973-4"
copyright = "Theme by <a href='https://github.com/MeiK2333/github-style'>github-style</a>"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "MeiK"
  github = "MeiK2333"
  description = "In solitude, where we are least alone."
  twitter = "MeiK2333"
  email = "meik2333@gmail.com"
  utterances = "MeiK2333/MeiK2333.github.io"
  rss = true
  location = "China"
  lastmod = true
  enableGitalk = true
  headerIcon = "https://meik2333.com/images/avatar.png"

  [params.gitalk]
    clientID = "4d2994f790117e7633bd" # Your client ID
    clientSecret = "da68dfaa74148e8440fae500dcf1751a21cbbec3" # Your client secret
    repo = "MeiK2333.github.io"
    owner = "MeiK2333"
    admin = "MeiK2333"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
